from typing import Any, Literal, Optional, Union
from pydantic import BaseModel, Field


class ModelInfo(BaseModel):
    """Information about a single model."""

    id: str
    object: str
    created: int
    owned_by: str = "rhel-lightspeed"


class ModelsResponse(BaseModel):
    """Response containing list of available models."""

    object: str = "list"
    data: list[ModelInfo]


class Function(BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class ChatCompletionMessageToolCall(BaseModel):
    id: str
    """The ID of the tool call."""

    function: Function
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class ToolFunction(BaseModel):
    """Function definition for a tool."""

    name: str
    description: Optional[str] = None
    parameters: Optional[dict[str, Any]] = None


class Tool(BaseModel):
    """Tool definition for function calling."""

    type: Literal["function"] = "function"
    function: ToolFunction


class ChatMessage(BaseModel):
    """A single message in a chat conversation."""

    role: Literal["system", "user", "assistant", "tool"] = "user"
    content: Optional[str] = None
    tool_calls: Optional[list[ChatCompletionMessageToolCall]] = None
    tool_call_id: Optional[str] = None  # For tool role messages
    name: Optional[str] = None  # For function/tool messages


class ChatCompletionRequest(BaseModel):
    """OpenAI-compatible chat completion request."""

    messages: list[ChatMessage] = Field(
        ..., description="list of messages in the conversation"
    )
    stream: bool = Field(default=False, description="Whether to stream responses")
    tools: Optional[list[Tool]] = Field(
        default=None, description="list of tools the model can call"
    )
    tool_choice: Optional[Union[str, dict[str, Any]]] = Field(
        default=None, description="Controls which tool is called"
    )


class CompletionUsage(BaseModel):
    """Token usage statistics for a completion."""

    prompt_tokens: int
    completion_tokens: int
    total_tokens: int


class ChatCompletionChoice(BaseModel):
    """A single completion choice."""

    index: int
    message: ChatMessage
    finish_reason: Optional[
        Literal["stop", "length", "tool_calls", "content_filter"]
    ] = None
    logprobs: Optional[Any] = None


class ChatCompletionResponse(BaseModel):
    """OpenAI-compatible chat completion response."""

    id: str
    object: str = "chat.completion"
    created: int
    model: str
    choices: list[ChatCompletionChoice]
    usage: Optional[CompletionUsage] = None
    system_fingerprint: Optional[str] = None
